name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Build Ionic and copy to Android
      run: |
        ionic build --prod
        ionic capacitor sync android

    - name: Grant execute permission for gradlew
      working-directory: ./android
      run: chmod +x gradlew

    - name: Build debug with Gradle
      working-directory: ./android
      run: ./gradlew build -x lintDebug
      
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: apk-debug
        path: |
          ./android/app/build/outputs/apk/debug
        retention-days: 14
